Fix ROOTPART on virtual environment, thanks to Francisco José R. M. for pointing out to the culprit!

diff --git a/debian/kernel/postinst.d/z50-raspi-firmware b/debian/kernel/postinst.d/z50-raspi-firmware
--- a/debian/kernel/postinst.d/z50-raspi-firmware
+++ b/debian/kernel/postinst.d/z50-raspi-firmware
@@ -44,8 +44,12 @@ if [ -z "$latest_initrd" ]; then
 fi
 
 # Default configurations, overridable at /etc/default/raspi-firmware
+#
+# Added an '|| true' to findmnt to avoid its failure breaking the install
+# running under a container or virtual environment that does not provide
+# a usable /proc
 CMA=64M
-ROOTPART=`findmnt -n --output=source /`
+ROOTPART=`findmnt -n --output=source /` || true
 if [ -z "$ROOTPART" ]; then ROOTPART=/dev/mmcblk0p2;fi
 KERNEL="auto"
 INITRAMFS="auto"
